CC=g++

prog1: esercizio1.cc
	$(CC) -o $@ $<

esegui1:
	./prog1
	
prog2: esercizio2.cc
	$(CC) -o $@ $<

esegui2:
	./prog2

prog3: esercizio3.cc
	$(CC) -o $@ $<

esegui3:
	./prog3

prog4: esercizio4.cc
	$(CC) -o $@ $<

esegui4:
	./prog4

prog5: esercizio5.cc
	$(CC) -o $@ $<

esegui5:
	./prog5
