CC=g++

prog1: esercizio1.cc
	$(CC) -o $@  $< `root-config --cflags` `root-config --libs`
	
esegui1:
	./prog1

prog2: esercizio2.cc
	$(CC) -o $@  $< `root-config --cflags` `root-config --libs`
	
esegui2:
	./prog2
