CC=g++

prog1: esercizio1.cc
	$(CC) -o $@ $<

esegui1:
	./prog1

prog2: esercizio2.cc funzioni.cc
	$(CC) -o $@ $< funzioni.cc

esegui2:
	./prog2

prog4: esercizio4.C
	$(CC) -o $@ $<

esegui4:
	./prog4
