CC=g++

prog3: esercizio3.cc
	$(CC) -o $@ $< `root-config --cflags` `root-config --libs`
	
esegui3:
	./prog3

prog4: esercizio4.cc
	$(CC) -o $@ $< `root-config --cflags` `root-config --libs`
	
esegui4:
	./prog4

prog5: esercizio5.cc
	$(CC) -o $@ $< `root-config --cflags` `root-config --libs`
	
esegui5:
	./prog5
